### ISSUE TITLE
Use explicit names for Discriminators

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#268]
This is now in DKPro Lab now and should be applied in TC. See https://github.com/dkpro/dkpro-lab/issues/82.

**Comment by Horsmann** [comment]
@daxenberger @zesch 
All that is to do here is giving each `Discriminator` a name and defining those names in the `Constants` class?

**Comment by daxenberger** [comment]
> All that is to do here is giving each Discriminator a name and defining those names in the Constants class?

As far as I see, yes.

**Comment by Horsmann** [comment]
`WekaAblationDemo` and some other demos use a dimension `readers` which is not mapped as constant and I don't find the `@Discriminator` that maps this value to a variable? I found the `READER_TRAIN` and `READER_TEST` dimension, but not this one. Where is it defined?

**Comment by daxenberger** [comment]
`readers` is a `DimensionBundle`which is never explicitly called by it's name but only by the names of the dimensions it bundles (e.g. `READER_TRAIN`). The name is thus quite arbitrary.

**Comment by Horsmann** [comment]
Ok then we can leave it as it is if Jenkins doesn't complain we can close this one.

**Comment by Horsmann** [comment]
Build fails but seems Artifactory related - service not available
@reckart  Is zoidberg down for maintenance or did I break something?

```
/tmp/settings4590813468708005506.xml
[ERROR] uniqueVersion == false is not anymore supported in maven 3
[INFO] Deployment in dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local (id=ukp-oss,uniqueVersion=false)
Deploying the main artifact dkpro-tc-0.9.0-SNAPSHOT.pom
Downloading: dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local/org/dkpro/tc/dkpro-tc/0.9.0-SNAPSHOT/maven-metadata.xml
ERROR: Failed to retrieve remote metadata org.dkpro.tc:dkpro-tc:0.9.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.dkpro.tc:dkpro-tc:0.9.0-SNAPSHOT/maven-metadata.xml from/to ukp-oss (dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local): Failed to transfer file: https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local/org/dkpro/tc/dkpro-tc/0.9.0-SNAPSHOT/maven-metadata.xml. Return code is: 503
org.apache.maven.artifact.deployer.ArtifactDeploymentException: Failed to retrieve remote metadata org.dkpro.tc:dkpro-tc:0.9.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.dkpro.tc:dkpro-tc:0.9.0-SNAPSHOT/maven-metadata.xml from/to ukp-oss (dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local): Failed to transfer file: https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local/org/dkpro/tc/dkpro-tc/0.9.0-SNAPSHOT/maven-metadata.xml. Return code is: 503
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:143)
    at hudson.maven.reporters.MavenArtifactRecord.deploy(MavenArtifactRecord.java:193)
    at hudson.maven.RedeployPublisher.perform(RedeployPublisher.java:176)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:776)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1047)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:381)
Caused by: org.eclipse.aether.deployment.DeploymentException: Failed to retrieve remote metadata org.dkpro.tc:dkpro-tc:0.9.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.dkpro.tc:dkpro-tc:0.9.0-SNAPSHOT/maven-metadata.xml from/to ukp-oss (dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local): Failed to transfer file: https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local/org/dkpro/tc/dkpro-tc/0.9.0-SNAPSHOT/maven-metadata.xml. Return code is: 503
    at org.eclipse.aether.internal.impl.DefaultDeployer.upload(DefaultDeployer.java:470)
    at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:314)
    at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:269)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:139)
    ... 11 more
```

**Comment by reckart** [comment]
@Horsmann zoidberg is undergoing maintenance which took some unexpected turns. @betoboullosa is on it.
