### ISSUE TITLE
SVMHMM: crashes with BatchTrainTestReport

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#284]
Hi,

for testing purposes I added the BatchTrainTestReport.class as report to the `BrownPosSVMHMMDemo` in the `de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence` package

I returned to an older commit a50600 to make sure that this bug was not newly introduced by the latest changes. It remained unnoticed because the Demo did not make use of any reports. Which module is supposed to create this results.prop? 

The execution eventually fails with this exception:

```
de.tudarmstadt.ukp.dkpro.lab.engine.LifeCycleException: org.springframework.dao.DataAccessResourceFailureException: Unable to access [results.prop] in context [SVMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de3e8c301]; nested exception is java.io.FileNotFoundException: target/results/BrownPosSVMHMMDemo/de.tudarmstadt.ukp.dkpro.lab/repository/SVMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de3e8c301/results.prop (No such file or directory)
280297 [main] INFO de.tudarmstadt.ukp.dkpro.lab.logging.impl.DefaultLoggingService  - [Evaluation-BrownTrainTestBatchTask-26520a7a-65f2-11e5-9d23-099de3e8c301] Shut down task
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(DefaultLifeCycleManager.java:154)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:159)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:53)
    at de.tudarmstadt.ukp.dkpro.lab.Lab.run(Lab.java:108)
    at de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence.BrownPosSVMHMMDemo.runTrainTest(BrownPosSVMHMMDemo.java:155)
    at de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence.BrownPosSVMHMMDemo.main(BrownPosSVMHMMDemo.java:190)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Unable to access [results.prop] in context [SVMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de3e8c301]; nested exception is java.io.FileNotFoundException: target/results/BrownPosSVMHMMDemo/de.tudarmstadt.ukp.dkpro.lab/repository/SVMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de3e8c301/results.prop (No such file or directory)
    at de.tudarmstadt.ukp.dkpro.lab.storage.filesystem.FileSystemStorageService.retrieveBinary(FileSystemStorageService.java:227)
    at de.tudarmstadt.ukp.dkpro.tc.ml.report.BatchTrainTestReport.execute(BatchTrainTestReport.java:82)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(DefaultLifeCycleManager.java:147)
    ... 5 more
Caused by: java.io.FileNotFoundException: target/results/BrownPosSVMHMMDemo/de.tudarmstadt.ukp.dkpro.lab/repository/SVMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de3e8c301/results.prop (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at de.tudarmstadt.ukp.dkpro.lab.storage.filesystem.FileSystemStorageService.retrieveBinary(FileSystemStorageService.java:195)
    ... 7 more´´´
```

**Comment by daxenberger** [comment]
Hi Tobias,

results.prop (as defined in Constants.RESULTS_FILENAME) is the name of a
file generated by the ML TestTask which holds the results of the internal
evaluation carried out by the ML framework (copied to the final results
file, or averaged in case of CV). This has not been implemented for each
ML framework (apparently not for SVMHMM) and should be replaced anyway by
the using the new evaluation module which aggregates the results of
id2outcome and calculates the evaluation score individually of the
underlying ML framework (cf. BatchTrainTestUsingTCEvaluationReport).

Hope this helps,
Johannes

Von:  Tobias Horsmann notifications@github.com
Antworten an:  dkpro/dkpro-tc
<reply+00af7dcd0dd9828af746e4ba5d70cb1e10c7399cd8300c6992cf0000000112211abd
92a169ce067a4ccc@reply.github.com>
Datum:  Montag, 28. September 2015 17:11
An:  dkpro/dkpro-tc dkpro-tc@noreply.github.com
Betreff:  [dkpro-tc] SVMHMM: crashes with BatchTrainTestReport (#284)

Hi,
for testing purposes I added the BatchTrainTestReport.class as report to
the 
BrownPosSVMHMMDemo in the
de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence package
The execution eventually fails with this exception:
de.tudarmstadt.ukp.dkpro.lab.engine.LifeCycleException:
org.springframework.dao.DataAccessResourceFailureException: Unable to
access [results.prop] in context
[SVMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de
3e8c301]; nested exception is java.io.FileNotFoundException:
target/results/BrownPosSVMHMMDemo/de.tudarmstadt.ukp.dkpro.lab/repository/S
VMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de3e
8c301/results.prop (No such file or directory)
280297 [main] INFO 
de.tudarmstadt.ukp.dkpro.lab.logging.impl.DefaultLoggingService  -
[Evaluation-BrownTrainTestBatchTask-26520a7a-65f2-11e5-9d23-099de3e8c301]
Shut down task
    at 
de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(D
efaultLifeCycleManager.java:154)
    at 
de.tudarmstadt.ukp.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngin
e.java:159)
    at 
de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(De
faultTaskExecutionService.java:53)
    at de.tudarmstadt.ukp.dkpro.lab.Lab.run(Lab.java:108)
    at 
de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence.BrownPosSVMHMMDemo.run
TrainTest(BrownPosSVMHMMDemo.java:155)
    at 
de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence.BrownPosSVMHMMDemo.mai
n(BrownPosSVMHMMDemo.java:190)
Caused by: org.springframework.dao.DataAccessResourceFailureException:
Unable to access [results.prop] in context
[SVMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de
3e8c301]; nested exception is java.io.FileNotFoundException:
target/results/BrownPosSVMHMMDemo/de.tudarmstadt.ukp.dkpro.lab/repository/S
VMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de3e
8c301/results.prop (No such file or directory)
    at 
de.tudarmstadt.ukp.dkpro.lab.storage.filesystem.FileSystemStorageService.re
trieveBinary(FileSystemStorageService.java:227)
    at 
de.tudarmstadt.ukp.dkpro.tc.ml.report.BatchTrainTestReport.execute(BatchTra
inTestReport.java:82)
    at 
de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(D
efaultLifeCycleManager.java:147)
    ... 5 more
Caused by: java.io.FileNotFoundException:
target/results/BrownPosSVMHMMDemo/de.tudarmstadt.ukp.dkpro.lab/repository/S
VMHMMRandomTestTask-BrownTrainTestBatchTask-27bf2f10-65f2-11e5-9d23-099de3e
8c301/results.prop (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at 
de.tudarmstadt.ukp.dkpro.lab.storage.filesystem.FileSystemStorageService.re
trieveBinary(FileSystemStorageService.java:195)
    ... 7 more```

I returned to an older commit a50600 to make sure that this bug was not
newly introduced by the latest changes. It remained unnoticed because the
Demo did not make use of any reports. Which module is supposed to create
this results.prop? 
�
Reply to this email directly or
view it on GitHub https://github.com/dkpro/dkpro-tc/issues/284.

**Comment by Horsmann** [comment]
Hi
thanks so far.

I added the `SVMHMMOutcomeIDReport.class` as report hoping it would create the id2outocome report for the new evaluation modules, but unfortunately this report crashes as well.

The report has a method `loadGoldAndPredictedLabels()` which is called several times. It looks for a mapping file which is located in the `SVMHMM-**/output` folder. This file is found for the first few calls, but for reasons I don't fully understand it is called at the end an additional time - this time it looks for the mapping file in the `Evaluation-**/output` folder where it is naturally not found and fails with an FileNotFoundException.

This error is easily reproducible by adding `batch.addReport(SVMHMMOutcomeIDReport.class);` to the `BrownPosSVMHMMDemo` in TC. I am having problems to understand where this last call is coming from. Any ideas?   

``````
de.tudarmstadt.ukp.dkpro.lab.engine.LifeCycleException: java.io.FileNotFoundException: target/results/BrownPosSVMHMMDemo/de.tudarmstadt.ukp.dkpro.lab/repository/Evaluation-BrownTrainTestBatchTask-d76fd3dc-668d-11e5-8c7a-dfa293624473/output/labelsToIntegersMapping_DualTreeBidiMap.bin (No such file or directory)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(DefaultLifeCycleManager.java:154)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:159)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:53)
    at de.tudarmstadt.ukp.dkpro.lab.Lab.run(Lab.java:108)
    at de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence.BrownPosSVMHMMDemo.runTrainTest(BrownPosSVMHMMDemo.java:155)
    at de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence.BrownPosSVMHMMDemo.main(BrownPosSVMHMMDemo.java:190)
Caused by: java.io.FileNotFoundException: target/results/BrownPosSVMHMMDemo/de.tudarmstadt.ukp.dkpro.lab/repository/Evaluation-BrownTrainTestBatchTask-d76fd3dc-668d-11e5-8c7a-dfa293624473/output/labelsToIntegersMapping_DualTreeBidiMap.bin (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at de.tudarmstadt.ukp.dkpro.tc.svmhmm.util.SVMHMMUtils.loadMapping(SVMHMMUtils.java:209)
    at de.tudarmstadt.ukp.dkpro.tc.svmhmm.report.SVMHMMOutcomeIDReport.loadGoldAndPredictedLabels(SVMHMMOutcomeIDReport.java:84)
    at de.tudarmstadt.ukp.dkpro.tc.svmhmm.report.SVMHMMOutcomeIDReport.execute(SVMHMMOutcomeIDReport.java:104)
    at de.tudarmstadt.ukp.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(DefaultLifeCycleManager.java:147)
    ... 5 more```
``````

**Comment by daxenberger** [comment]
Tobias, have you had a look at de.tudarmstadt.ukp.dkpro.tc.svmhmm.SVMHMMAdapter? The adapter specifies all necessary reports and at least in the respective demo (BrownPosSVMHMMDemo), they appear to work.

**Comment by daxenberger** [comment]
@Horsmann: How did you finally resolve this one?

**Comment by Horsmann** [comment]
I think there is just no report for calculating accuracy so I hacked an own additional report for counting by using one of the files that are created. The module does not create a outcome2Id report, at least not in the format of the others. Instead a `outcomesGoldPredicted.csv` is created which is not exactly the same.
