### ISSUE TITLE
Dimensions are not declared as discriminators

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-tc#398]
When running the method _runCrossValidationWithStatsEval_ in the example WekaTwentyNewsgroupsDemo, the the following error occurs:

```
Exception in thread "main" org.dkpro.lab.engine.LifeCycleException: org.dkpro.tc.api.exception.TextClassificationException: baselineClassificationArgs not found in discriminators set.
at org.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(DefaultLifeCycleManager.java:144)
at org.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:159)
at org.dkpro.lab.engine.impl.BatchTaskEngine.runNewExecution(BatchTaskEngine.java:341)
at org.dkpro.lab.engine.impl.BatchTaskEngine.executeConfiguration(BatchTaskEngine.java:235)
at org.dkpro.lab.engine.impl.BatchTaskEngine.run(BatchTaskEngine.java:133)
at org.dkpro.lab.engine.impl.DefaultTaskExecutionService.run(DefaultTaskExecutionService.java:52)
at org.dkpro.lab.Lab.run(Lab.java:113)
at org.dkpro.tc.examples.single.document.WekaTwentyNewsgroupsDemo.runCrossValidationWithStatsEval(WekaTwentyNewsgroupsDemo.java:188)
at org.dkpro.tc.examples.single.document.WekaTwentyNewsgroupsDemo.main(WekaTwentyNewsgroupsDemo.java:92)
Caused by: org.dkpro.tc.api.exception.TextClassificationException: baselineClassificationArgs not found in discriminators set.
at org.dkpro.tc.core.util.ReportUtils.getDiscriminatorValue(ReportUtils.java:347)
at org.dkpro.tc.ml.report.BatchStatisticsTrainTestReport.execute(BatchStatisticsTrainTestReport.java:74)
at org.dkpro.lab.engine.impl.DefaultLifeCycleManager.complete(DefaultLifeCycleManager.java:137)
```

Required dimensions which are required for the reports are not declared (as discriminators)

The required dimension are added to the parameter space, but not recognized by the reports.

**Comment by Horsmann** [comment]
@reckart  Do you have an idea how a dimension might be lost on the way :/

**Comment by zesch** [comment]
You can declare as many dimensions as you want, but if there is no discriminator to get the value it is just ignored.

**Comment by reckart** [comment]
Maybe there are nested tasks and something broke the inheritance of the outer parameter space into the inner parameter space?

**Comment by reckart** [comment]
@zesch +1 ;)

**Comment by nicolaierbs** [comment]
I just added 

```
@Discriminator(name=DIM_BASELINE_CLASSIFICATION_ARGS)
protected List<String> baselineClassificationArguments;
@Discriminator(name=DIM_BASELINE_FEATURE_SET)
protected List<TcFeature> baselineFeatureSet;
```

to WekaTestTask and it works, but I guess it is supposed to do something with the values...

**Comment by Horsmann** [comment]
This feature probably got lost when enabling using the same features with various configurations. Was not intended. The easy solution is to simply call the pipeline twice with a different feature set. I tend to flag this `won't fix`

**Comment by daxenberger** [comment]
In this particular setup, the baseline classification args are required within the same run, to calculate significance scores. 
However, the "stats-eval" scenario has not really been kept up-to-date with the last releases - so we should either update the whole module properly or discard it altogether.
I might have a look at this in the next days.
