### ISSUE TITLE
Update Lab to 0.14.0-SNAPSHOT to enable instances of reports

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#400]
Lab snapshot can now use instances of reports instead of only passing the .class files

**Comment by Horsmann** [comment]
@reckart The groovy scripts don't like instances of reports.
I don't really get the problem here. What exactly is groovies problem? The java code works as usual but some background-magic starts to fail with the groovy scripts.

```
, machineLearningAdapter=class org.dkpro.tc.ml.weka.WekaRegressionAdapter, parameterSpace=[[readers: ?], [learningMode: ?], [featureMode: ?], [classificationArguments: ?], [featureSet: ?]], executionPolicy=RUN_AGAIN, reports=class org.dkpro.tc.ml.report.BatchTrainTestReport}' with class 'java.util.LinkedHashMap' to class 'org.dkpro.tc.ml.ExperimentTrainTest' due to: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'class org.dkpro.tc.ml.report.BatchTrainTestReport' with class 'java.lang.Class' to class 'java.util.List'
	at org.dkpro.tc.groovyexamples.regression.pair.RegressionDemo.runTrainTest(RegressionDemo.groovy:138)
	at org.dkpro.tc.groovyexamples.regression.pair.RegressionDemo.main(RegressionDemo.groovy:164)
```

Reports are currently passed like this:
```
        ExperimentTrainTest batchTask = [
            experimentName: experimentName + "-TrainTest-Groovy",
            // we need to explicitly set the name of the batch task, as the constructor of the groovy setup must be zero-arg
            type: "Evaluation-"+ experimentName +"-TrainTest-Groovy",
            preprocessing:  getPreprocessing(),
            machineLearningAdapter: WekaRegressionAdapter,
            parameterSpace : [
                dimReaders,
                dimLearningMode,
                dimFeatureMode,
                dimClassificationArgs,
                dimFeatureSets
            ],
            executionPolicy: ExecutionPolicy.RUN_AGAIN,
            reports:[
                BatchTrainTestReport
                ]
        ]
```

How do I fix this or why is the auto-cast magic failing here?

**Comment by Horsmann** [comment]
@reckart ping

**Comment by reckart** [comment]
No clue. Can this be tested by running code from the repo?

**Comment by Horsmann** [comment]
yes. so far I see every `Groovy` test case runs into this error (update your snapshot versions to use a new 0.14.-SNAPSHOT)

**Comment by reckart** [comment]
Why is the Jenkins-build green then?

**Comment by Horsmann** [comment]
The TC build is `yellow`. The Lab build passes. It is just the pairing of groovy with the recent change that fails.

**Comment by Horsmann** [comment]
@reckart ping

**Comment by reckart** [comment]
I currently don't find the time to look at it.

**Comment by Horsmann** [comment]
wontfix
